name: Deploy to Hosted Service

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Yarn
        run: npm i -g yarn
      - name: Install Libs
        run: yarn --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      # - name: Run Unit Tests
      #   run: yarn test:unit
      - name: Deploy to Hosted Service
        run: |
          npx graph deploy aavegotchi-gotchi-vault \
            --deploy-key ${{ secrets.SATSUMA_ACCESS_TOKEN }} \
            --node https://subgraphs.alchemy.com/api/subgraphs/deploy \
            --ipfs https://ipfs.satsuma.xyz \
            --version-label ${GITHUB_REF#refs/*/}
        shell: bash
